version: '3.4'

services:
  coursetracker.api:
    image: coursetrackercr.azurecr.io/coursetrackerapi
    build:
      context: .
      dockerfile: CourseTracker.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5006
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5006:5006"

  coursetracker.ui:
    image: coursetrackercr.azurecr.io/coursetrackeruimvc
    build:
      context: .
      dockerfile: CourseTracker.UI/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5005
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5005:5005"